### ISSUE TITLE
Bug validasi minimal karakter password & trouble pada .env

### ISSUE THREAD

**Issue by deriscode** [berbinarbinar/binar-challenge-chapter-8#7]
### Trouble pada .env
dotenv belum di-import pada file app.js

### Bug validasi minimal karakter password
Ada bug ketika membuat akun player. Di mana validasi yg mengharuskan membuat password dengan minimal 6 karakter, tidak berjalan.

Penyebabnya berdasarkan hasil diskusi saya bersama teman-teman & fasilitator adalah karena pengaruh bcrypt yg membuat password setelah di-hashing menjadi banyak karakter.

Berikut adalah solusi yg kami gunakan, kami membuat logika pengecekan di API createPlayer.
Pengecekan tersebut dilakukan sebelum kode membuat player dijalankan

![carbon_bugcode](https://user-images.githubusercontent.com/94205149/160310693-5662b04a-1cdb-4581-824d-385d8a1b392d.png)

**Comment by icanq** [comment]
ah yes you can open up the pull request, thanks a lot!
